---
title: "Untitled"
author: "Bruno Crotman"
date: "28/04/2020"
output: slidy_presentation
---

```{r}

library(tidyverse)
library(tidymodels)
library(lubridate)
library(feather)

```


## Brincadeira Tidymodels

```{r}



calendario <- read_csv("airbnb/calendar.csv")

anuncios <- read_csv("airbnb/listings.csv")

calendario_selecao <-  calendario %>% 
    mutate(
        across(where(is.numeric), as.integer) 
    ) %>% 
    mutate(
        price = str_remove(price, "\\$") %>% parse_number() %>% as.integer(),
        adjusted_price = str_remove(adjusted_price, "\\$") %>% parse_number() %>%  as.integer(),
        listing_id = as.integer(listing_id)
    ) %>% 
    filter(
        date < make_date(2020,3,1)        
    )

anuncios_selecao <- anuncios %>% 
    mutate(
        id = as.integer(id),
        neighbourhood_cleansed = as_factor(neighbourhood_cleansed),
        room_type == as_factor(room_type)
    ) %>% 
    mutate(
        across(where(is.numeric), as.integer) 
    ) %>% 
    select(
        id,
        neighbourhood_cleansed,
        host_is_superhost,
        accommodates,
        starts_with("review_"),
        room_type

    ) %>% 
    filter(
        !is.na(host_is_superhost)
    ) %>% 
    rowwise() %>% 
    mutate(
        mean_review = mean(c_across(starts_with("review") & !matches("rating")    )),
        review_scores_rating = review_scores_rating/10
    ) %>% 
    ungroup()


anuncios_calendario <- anuncios_selecao %>% 
    left_join(
        calendario_selecao,
        by = c("id" = "listing_id")
    ) 
    

write_feather(anuncios_calendario, "airbnb/anuncios_calendario.feat")


```



```{r}

ggplot(anuncios_calendario) +
    geom_density(
        aes(
            x = price,
            color = neighbourhood_cleansed 
        )
    )


```




```{r}



ggplot(anuncios_calendario) +
    geom_histogram(
        aes(
            x = review_scores_rating,
            y = after_stat(density),
            fill = neighbourhood_cleansed
        ),
        binwidth = 1,
        position = "dodge"
        
    )



```




```{r demanda, echo=FALSE}


por_preco <- tibble(
    preco_min = seq(45, to = 345, by = 10),
    preco_max = seq(55, to = 355, by = 10),
    preco_medio = seq(50, to = 350, by = 10)
)  
    
demanda <- por_preco %>% 
    crossing(anuncios_calendario) %>% 
    filter(
        preco_min <= price,
        preco_max > price
    )

ocupacao <- demanda %>% 
    group_by(
        preco_medio,
        host_is_superhost,
        neighbourhood_cleansed
    ) %>% 
    summarise(ocupacao = sum(available)/n())


ggplot(ocupacao,
        aes(
            x = preco_medio,
            y = ocupacao,
            color = host_is_superhost
        )
       
       ) +
    geom_point(
    ) +
    geom_smooth(se = FALSE) +
    facet_wrap(~neighbourhood_cleansed) +
    theme_minimal() +
    theme(
        legend.position = "top"
    ) 



```











